# Generated by Django 5.2.9 on 2025-12-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelconfig',
            name='feature_weights',
        ),
        migrations.RemoveField(
            model_name='modelconfig',
            name='hyperparameters',
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='max_depth',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='min_samples_split',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='n_estimators',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_draw_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_form',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_goal_avg',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_injuries',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_away_win_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_form_diff',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_advantage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_draw_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_form',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_goal_avg',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_injuries',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_strength',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_home_win_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='weight_strength_diff',
            field=models.FloatField(default=1.0),
        ),
    ]
